# Generated by Django 4.2.7 on 2026-01-15 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('submitted', 'Сдан мастером')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='MonthlyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день месяца', verbose_name='Месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_monthly_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Месячный табель',
                'verbose_name_plural': 'Месячные табели',
                'unique_together': {('month', 'master')},
            },
        ),
    ]
