# Generated by Django 4.2.7 on 2026-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_timesheet_status_monthlytimesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('holiday', 'Праздник'), ('preholiday', 'Предпраздник')], default='holiday', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
