# Generated by Django 4.2.7 on 2026-03-04 13:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_is_foundry_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Год')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество талонов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_vouchers', to='users.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Талоны на молоко',
                'verbose_name_plural': 'Талоны на молоко',
                'indexes': [models.Index(fields=['year', 'month'], name='timesheet_m_year_2387f2_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
