# Generated by Django 4.2.7 on 2026-03-04 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0004_milkvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionMilkAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, unique=True, verbose_name='Должность')),
                ('per_day_count', models.PositiveIntegerField(default=0, verbose_name='Талонов в день')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Норма талонов по должности',
                'verbose_name_plural': 'Нормы талонов по должностям',
                'ordering': ['position'],
            },
        ),
    ]
