# Generated by Django 4.2.15 on 2026-03-23 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_employee_is_itr_employee_user_is_itr_master'),
        ('timesheet', '0005_positionmilkallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItrTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('value', models.CharField(help_text='Часы работы (1-24) или условное обозначение', max_length=10, verbose_name='Значение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('submitted', 'Сдан мастером')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_itr_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Утверждено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_timesheets', to='users.employee', verbose_name='Сотрудник')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Табель ИТР',
                'verbose_name_plural': 'Табели ИТР',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['date', 'employee'], name='timesheet_i_date_646652_idx'), models.Index(fields=['status', 'date'], name='timesheet_i_status_5ecfd8_idx')],
                'unique_together': {('date', 'employee')},
            },
        ),
    ]
