# Generated by Django 6.0.1 on 2026-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shop_chief_name',
            field=models.CharField(blank=True, default='С.В. Ефременко', help_text='ФИО начальника цеха, например: С.В. Ефременко', max_length=200, verbose_name='Начальник цеха (ФИО)'),
        ),
    ]
