# Generated by Django 6.0.1 on 2026-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_department_shop_chief_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('master', 'Мастер'), ('planner', 'Плановый отдел'), ('worker', 'Работник')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
