# Generated by Django 4.2.7 on 2026-02-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_options_employee_department_own_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.employee', verbose_name='Сотрудник')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
                'indexes': [models.Index(fields=['master', 'start_date', 'end_date'], name='users_emplo_master__db0a22_idx'), models.Index(fields=['employee', 'start_date', 'end_date'], name='users_emplo_employe_379a6c_idx')],
            },
        ),
    ]
