# Generated by Django 4.2.7 on 2026-02-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employeeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_chief_name_override',
            field=models.CharField(blank=True, help_text='Если указано, переопределяет ФИО начальника цеха из отдела в печатной форме', max_length=200, verbose_name='Начальник цеха (ФИО) для печати'),
        ),
    ]
