# Generated by Django 4.2.7 on 2026-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_shop_chief_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_self_in_own_timesheet',
            field=models.BooleanField(default=True, help_text='Если выключено — ваша строка не будет отображаться в вашем табеле', verbose_name='Показывать себя в своём табеле'),
        ),
    ]
