# Generated by Django 4.2.7 on 2026-03-02 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_show_self_in_own_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'master'}, related_name='permitted_planners', to=settings.AUTH_USER_MODEL, verbose_name='Доступные мастера (для планового отдела)'),
        ),
    ]
