# Generated by Django 4.2.7 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_allowed_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_foundry',
            field=models.BooleanField(default=False, help_text='Работает по литейному графику', verbose_name='Литейщик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('master', 'Мастер'), ('planner', 'Плановый отдел'), ('tb', 'ТБ'), ('worker', 'Работник')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
