# Generated by Django 4.2.7 on 2026-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_is_foundry_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_foundry_master',
            field=models.BooleanField(default=False, help_text='Если включено — все сотрудники этого мастера работают по литейному графику', verbose_name='Мастер литейного графика'),
        ),
    ]
