# Generated by Django 4.2.7 on 2026-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_foundry_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foundry_anchor_date',
            field=models.DateField(blank=True, help_text='Дата, с которой начинается цикл литейного графика для сотрудников мастера', null=True, verbose_name='Якорь литейного графика'),
        ),
    ]
