# Generated by Django 4.2.7 on 2026-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_foundry_anchor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ic_schedule_override',
            field=models.CharField(choices=[('inherit', 'Наследовать от мастера'), ('always_8', 'Всегда 8'), ('weekdays', 'Только выбранные дни недели')], default='inherit', max_length=20, verbose_name='ИЦ: режим'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ic_weekdays',
            field=models.CharField(blank=True, help_text='Через запятую: 0..6 (0=Пн). Пример: 0,2,4', max_length=50, verbose_name='ИЦ: дни недели'),
        ),
        migrations.AddField(
            model_name='user',
            name='ic_anchor_date',
            field=models.DateField(blank=True, help_text='Дата, с которой начинается недельный цикл графика ИЦ', null=True, verbose_name='Якорь графика ИЦ'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ic_master',
            field=models.BooleanField(default=False, help_text='Если включено — сотрудники мастера работают по графику ИЦ (неделя 8 / неделя 8/2)', verbose_name='Мастер ИЦ'),
        ),
    ]
