# Generated by Django 4.2.15 on 2026-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employee_ic_schedule_override_employee_ic_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_itr_employee',
            field=models.BooleanField(default=False, help_text='Если включено — сотрудник будет в отдельном табеле ИТР своего мастера', verbose_name='ИТР: показывать в табеле ИТР'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_itr_master',
            field=models.BooleanField(default=False, help_text='Если включено — доступен отдельный табель ИТР', verbose_name='Мастер ИТР'),
        ),
    ]
