# Generated by Django 4.2.15 on 2026-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employee_is_itr_employee_user_is_itr_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_self_in_itr_timesheet',
            field=models.BooleanField(default=True, help_text='Если выключено — ваша строка не будет отображаться в вашем табеле ИТР', verbose_name='Показывать себя в табеле ИТР'),
        ),
    ]
