# Generated by Django 4.2.15 on 2026-03-23 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_show_self_in_itr_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ic_hours_per_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='ИЦ: часов в день'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ic_is_part_time',
            field=models.BooleanField(default=False, verbose_name='ИЦ: совместитель'),
        ),
    ]
