# Generated by Django 4.2.15 on 2026-03-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employee_ic_hours_per_day_employee_ic_is_part_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ic_dm_weekdays',
            field=models.CharField(blank=True, help_text='Через запятую: 0..6 (0=Пн). Пример: 0,2,4', max_length=50, verbose_name='ИЦ: дни ДМ'),
        ),
    ]
