# Generated by Django 4.2.15 on 2026-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_employee_foundry_anchor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ic_is_disabled_group2',
            field=models.BooleanField(default=False, verbose_name='ИЦ: инвалид 2 группы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='foundry_anchor_date',
            field=models.DateField(blank=True, help_text='Если задано — Первый день "8" в табеле (8 8 8 8 8 В В  7/3 7/3 7/3 7/3 В 8/2 8/2 8/2 8/2 В)', null=True, verbose_name='Литейщик: якорь графика'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ic_schedule_override',
            field=models.CharField(choices=[('inherit', 'Наследовать от мастера'), ('opposite', 'Противоположный мастеру'), ('always_8', 'Всегда 8'), ('weekdays', 'Только выбранные дни недели')], default='inherit', max_length=20, verbose_name='ИЦ: режим'),
        ),
    ]
